let IS_FIRST_RUN = "is_first_run"
let MAP_TYPE = "map_type"
let UNZIP_FOLER_NAME = "unzip"
let SELECTED_FILE = "selected_file"
let SELECTED_FILE_PATH = "selected_file_path"
let START = "start"
let END = "end"
